// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnoijqdotgedaybvrrtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhub2lqcWRvdGdlZGF5YnZycnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5OTY3NDEsImV4cCI6MjA3OTU3Mjc0MX0.E78n2cT3Bqqzs-r2_bqK8sldv7cE3f1hHUQkQDH-_4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});